Controllers/ProgramController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LoginMVC.Controllers
{
    [Authorize(Roles = "1,2")]
    public class ProgramController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProviderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LoginMVC.Controllers
{
    [Authorize(Roles = "1,2")]
    public class ProviderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using LoginMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace LoginMVC.Controllers
{
    [Authorize(Roles = "1,3")]
    public class UserController : Controller
    {
        string BaseUrl = Urls.AuthUrl;
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(UserCreate user)
        {
            var accessToken = HttpContext.Session.GetString("Token");

            using(var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                client.BaseAddress = new Uri(BaseUrl);
                var stringContent = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8,"application/json");
                var postjob = client.PostAsync("users",stringContent);

                var result = postjob.Result;
                
                if(result.IsSuccessStatusCode){
                    return RedirectToAction("Index");
                }

                if(result.StatusCode == HttpStatusCode.Conflict){
                    ModelState.Clear();
                    TempData["Error"] = "Email Already Exists";
                    return View("Create");
                }
            }
            return View(user);
        }

        public ActionResult Delete(int Id)
        {
            var accessToken = HttpContext.Session.GetString("Token");
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                client.BaseAddress = new Uri(BaseUrl);

                var deleteTask = client.DeleteAsync("users?Id=" + Id.ToString());

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index","Home");
        }

       public IActionResult Index(string search)
        {
            var accessToken = HttpContext.Session.GetString("Token");
            IEnumerable<User> obj = null;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            client.BaseAddress = new Uri(BaseUrl);

            var apicall = client.GetAsync("users/func?Search=" + search);

            var read = apicall.Result;
            if(read.IsSuccessStatusCode)
            {
                var result = read.Content.ReadAsAsync<IList<User>>();
                result.Wait();
                obj = result.Result;

            }
            return View(obj);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using System.IdentityModel.Tokens.Jwt;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        *{
            font-family: "Roboto", sans-serif;
        }
        body{
            background-color: #f2f8f9;
        }
        
        #link::after {
            content: '';
            display: block;
            width: 0;
            height: 2px;
            background: white;
            transition: width .3s;
        }

        #link:hover::after {
            width: 100%;
            transition: width .3s;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-4">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width:120px;height:60px;object-fit:cover;" src="~/lib/Logo.png"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a id="link" class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">ManageUsers</a>
                        </li>
                        <li class="nav-item">
                            <a id="link" class="nav-link text-light" asp-area="" asp-controller="Provider" asp-action="Index">ManageProviders</a>
                        </li>
                        <li class="nav-item">
                            <a id="link" class="nav-link text-light" asp-area="" asp-controller="Program" asp-action="Index">ManagePrograms</a>
                        </li>
                    </ul>
                </div>
                
               @{
                 var token = @Context.Session.GetString("Token");
                 var handler = new JwtSecurityTokenHandler();

                 var name = handler.ReadJwtToken(token);
                 var getName = name.Claims.FirstOrDefault(c => c.Type == "User")?.Value;
                }
                  
                <div style="margin-right: 20px;color:white">Hello,  @getName</div>

                <form asp-controller="Login" asp-action="Logout" method="post">
                    <button class="btn btn-danger">Logout</button>
                </form>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>